[package]
name = "foo-tracer"
version = "0.1.0"
authors = ["Rust Example <rust-snippet@example.com>"]

[features]
default = ["bvh"]
go-faster = []
bvh = []

[dependencies]
indicatif = "0.9"
rand = "0.5"
rayon = "1.0"

[profile.release]
debug = true
opt-level = 3